// Input patterns only: words about not wanting to live or about self-harm, in Tagalog, Taglish or
// English. Any of them sends her to the crisis screen's fixed copy and NCMH 1553, before anything else.
// "Mamatay sa sakit" (dying of pain) is a figure of speech about pain and is left to the danger check.
const SELF_HARM =
  /\b(?:gusto|gusto\s+ko|gusto\s+kong|sana|mas\s+mabuti\s+pang?)\s+(?:na(?:ng)?\s+)?mamatay\b(?!\s+sa\s+(?:sakit|kirot))|\bmamatay\s+na\s+lang\b|\bmagpakamatay\b|\b(?:papatayin|patayin)\s+(?:ko\s+)?(?:na\s+)?(?:ang\s+)?sarili\b|\b(?:sasaktan|saktan)\s+(?:ko\s+)?(?:ang\s+)?sarili\b|\b(?:ayoko|ayaw\s+ko|ayaw\s+kong)\s+(?:na(?:ng)?\s+)?mabuhay\b|\bwala\s+(?:na(?:ng)?\s+)?(?:saysay|silbi|dahilan)\s+(?:ang\s+)?(?:buhay|mabuhay)\b|\bayoko\s+(?:na\s+)?sa\s+buhay(?:\s+ko)?\b|\bpagod\s+na\s+(?:ako\s+)?(?:sa\s+)?buhay\b|\bkill\s+myself\b|\bend(?:ing)?\s+(?:my\s+life|it\s+all)\b|\bsuicid\w*|\b(?:want|wanna|wish\s+I\s+could)\s+(?:to\s+)?die\b|\bdon'?t\s+want\s+to\s+(?:live|be\s+alive)\b|\bhurt\s+myself\b|\bself[-\s]?harm\b|\bbetter\s+off\s+dead\b|\b(?:gusto|gusto\s+ko|gusto\s+kong|sana)\s+(?:na(?:ng)?\s+)?(?:lang\s+)?(?:(?:akong|ako)\s+)?(?:mawala|maglaho)\b(?!\s+(?:na\s+)?(?:lang\s+)?(?:ang|yung|iyong|ng|sakit|kirot|pain))|\bsana\s+(?:hindi|di)\s+na\s+(?:ako\s+)?(?:magising|nagising)\b|\b(?:ayoko|ayaw\s+ko)\s+(?:na(?:ng)?\s+)?(?:gumising|magising)\b|\bmas\s+(?:mabuti|okay|ok|maganda)\s+(?:pa\s+)?kung\s+wala\s+na\s+ako\b|\btapusin\s+(?:ko\s+)?na\s+(?:ang\s+)?lahat\b|\b(?:want|wanna)\s+to\s+disappear\b|\bwish\s+I\s+(?:was|were|could\s+be)\s+(?:dead|gone)\b|\bwish\s+I\s+could\s+disappear\b|\bbetter\s+off\s+without\s+me\b|\bno\s+reason\s+to\s+live\b|\bdon'?t\s+want\s+to\s+wake\s+up\b/i;

export function mentionsSelfHarm(text: string): boolean {
  return SELF_HARM.test(text);
}
