// Generated by scripts/build-cards.mjs from sources/candidates.json; do not edit by hand.
import type { CardData } from './cards';

export const CARD_DATA: CardData[] = [
  {
    "id": "mcb-p4-warning-signs",
    "title": "DOH, Mother and Child Book (Philippines), p. 4",
    "quote": "If I experience any of the following warning signs, I should\nimmediately seek consultation at a health facility. Put a check (✔).\nSwelling of the legs, hands and/or face\nSevere headache, dizziness, blurring of vision\nVaginal bleeding\nPallor or anemia\nFever and chills\nVomiting\nFast or difficult breathing\nSevere abdominal pain\nVaginal discharge\nPainful urination\nWatery vaginal discharge\nConvulsions\nAbsence of/or reduced fetal movements\n(less than 10 kicks in 12 hours in the\nsecond half of pregnancy)",
    "source": "https://www.jica.go.jp/project/philippines/0600894/04/pdf/03_MCB01.pdf",
    "codes": [
      "vaginal_bleeding",
      "convulsions",
      "fever",
      "severe_headache",
      "visual_disturbance",
      "severe_abdominal_pain",
      "severe_difficulty_breathing"
    ],
    "stage": "pregnancy"
  },
  {
    "id": "mcb-p17-hygiene",
    "title": "DOH, Mother and Child Book (Philippines), p. 17",
    "quote": "Take a bath daily. Change sanitary pad every 4 to\n6 hours.",
    "source": "https://www.jica.go.jp/project/philippines/0600894/04/pdf/03_MCB01.pdf",
    "codes": [],
    "stage": "postpartum"
  },
  {
    "id": "mcb-p8-no-self-medication",
    "title": "DOH, Mother and Child Book (Philippines), p. 8",
    "quote": "I will not resort to self medication\nfor this can harm me and my baby",
    "source": "https://www.jica.go.jp/project/philippines/0600894/04/pdf/03_MCB01.pdf",
    "codes": [],
    "stage": "pregnancy"
  },
  {
    "id": "mcb-p8-emergency-prep",
    "title": "DOH, Mother and Child Book (Philippines), p. 8",
    "quote": "I will prepare for possible\nemergency (money,\nblood donor, transportation).",
    "source": "https://www.jica.go.jp/project/philippines/0600894/04/pdf/03_MCB01.pdf",
    "codes": [],
    "stage": "pregnancy"
  },
  {
    "id": "pcpnc-m2-danger-immediately",
    "title": "WHO, Pregnancy, childbirth, postpartum and newborn care: a guide for essential practice, 3rd edition (2015), M2, p. 163",
    "quote": "When to seek care on danger signs\nGo to the hospital or health centre immediately, day or night, DO NOT wait, if any of the\nfollowing signs:\nvaginal bleeding\nconvulsions/fits\nsevere headaches with blurred vision\nfever and too weak to get out of bed\nsevere abdominal pain\nfast or difficult breathing.",
    "source": "https://www.who.int/publications/i/item/9789241549356",
    "codes": [
      "vaginal_bleeding",
      "convulsions",
      "severe_headache",
      "visual_disturbance",
      "severe_abdominal_pain",
      "severe_difficulty_breathing"
    ],
    "stage": "pregnancy"
  },
  {
    "id": "pcpnc-m2-danger-soon",
    "title": "WHO, Pregnancy, childbirth, postpartum and newborn care: a guide for essential practice, 3rd edition (2015), M2, p. 163",
    "quote": "Go to the health centre as soon as possible if any of the following signs:\nfever\nabdominal pain\nwater breaks and not in labour after 6 hours\nfeel ill\nswollen fingers, face and legs.",
    "source": "https://www.who.int/publications/i/item/9789241549356",
    "codes": [
      "fever"
    ],
    "stage": "pregnancy"
  },
  {
    "id": "pcpnc-m2-labour-signs",
    "title": "WHO, Pregnancy, childbirth, postpartum and newborn care: a guide for essential practice, 3rd edition (2015), M2, p. 163",
    "quote": "Know the signs of labour\nIf you have any of these signs, go to the health centre as soon as you can.\nIf these signs continue for 12 hours or more, you need to go immediately.\nPainful contractions every 20 minutes or less.\nBag of water breaks.\nBloody sticky discharge.",
    "source": "https://www.who.int/publications/i/item/9789241549356",
    "codes": [
      "labour"
    ],
    "stage": "pregnancy"
  },
  {
    "id": "pcpnc-m2-any-concern",
    "title": "WHO, Pregnancy, childbirth, postpartum and newborn care: a guide for essential practice, 3rd edition (2015), M2, p. 163",
    "quote": "If at any time you have any concerns about your or your baby’s health, go to the health centre.",
    "source": "https://www.who.int/publications/i/item/9789241549356",
    "codes": [],
    "stage": "pregnancy"
  },
  {
    "id": "pcpnc-m2-rest",
    "title": "WHO, Pregnancy, childbirth, postpartum and newborn care: a guide for essential practice, 3rd edition (2015), M2, p. 163",
    "quote": "Rest when you can. Avoid lifting heavy objects.",
    "source": "https://www.who.int/publications/i/item/9789241549356",
    "codes": [],
    "stage": "pregnancy"
  },
  {
    "id": "pcpnc-m2-no-medication",
    "title": "WHO, Pregnancy, childbirth, postpartum and newborn care: a guide for essential practice, 3rd edition (2015), M2, p. 163",
    "quote": "Do not take medication unless prescribed at the health centre.",
    "source": "https://www.who.int/publications/i/item/9789241549356",
    "codes": [],
    "stage": "pregnancy"
  },
  {
    "id": "pcpnc-m4-danger-immediately",
    "title": "WHO, Pregnancy, childbirth, postpartum and newborn care: a guide for essential practice, 3rd edition (2015), M4, p. 165",
    "quote": "When to seek care for danger signs\nGo to hospital or health centre immediately, day or night, DO NOT wait, if any of the following signs:\nVaginal bleeding has increased.\nFits.\nFast or difficult breathing.\nFever and too weak to get out of bed.\nSevere headaches with blurred vision.\nCalf pain, redness or swelling; shortness of breath or chest pain.",
    "source": "https://www.who.int/publications/i/item/9789241549356",
    "codes": [
      "convulsions",
      "severe_difficulty_breathing",
      "severe_headache",
      "visual_disturbance"
    ],
    "stage": "postpartum"
  },
  {
    "id": "pcpnc-m4-danger-soon",
    "title": "WHO, Pregnancy, childbirth, postpartum and newborn care: a guide for essential practice, 3rd edition (2015), M4, p. 165",
    "quote": "Go to health centre as soon as possible if any of the following signs:\nSwollen, red or tender breasts or nipples.\nProblems urinating, or leaking.\nIncreased pain or infection in the perineum.\nInfection in the area of the wound.\nSmelly vaginal discharge.",
    "source": "https://www.who.int/publications/i/item/9789241549356",
    "codes": [],
    "stage": "postpartum"
  },
  {
    "id": "pcpnc-m4-hygiene",
    "title": "WHO, Pregnancy, childbirth, postpartum and newborn care: a guide for essential practice, 3rd edition (2015), M4, p. 165",
    "quote": "Wash all over daily, particularly the perineum.\nChange pad every 4 to 6 hours. Wash pad or dispose of it safely.",
    "source": "https://www.who.int/publications/i/item/9789241549356",
    "codes": [],
    "stage": "postpartum"
  },
  {
    "id": "pcpnc-m4-rest-water",
    "title": "WHO, Pregnancy, childbirth, postpartum and newborn care: a guide for essential practice, 3rd edition (2015), M4, p. 165",
    "quote": "Rest when you can.\nDrink plenty of clean, safe water.",
    "source": "https://www.who.int/publications/i/item/9789241549356",
    "codes": [],
    "stage": "postpartum"
  },
  {
    "id": "pcpnc-p170-delivery-go-now",
    "title": "WHO, Pregnancy, childbirth, postpartum and newborn care: a guide for essential practice, 3rd edition (2015), M9, p. 170",
    "quote": "If you or your baby has any of these signs, go to the hospital or health centre immediately,\nday or night, Do not wait.",
    "source": "https://www.who.int/publications/i/item/9789241549356",
    "codes": [],
    "stage": "pregnancy"
  },
  {
    "id": "pcpnc-p170-delivery-mother-signs",
    "title": "WHO, Pregnancy, childbirth, postpartum and newborn care: a guide for essential practice, 3rd edition (2015), M9, p. 170",
    "quote": "If waters break and not in labour after 6 hours.\nLabour pains (contractions) continue for more than 12 hours.\nHeavy bleeding (soaks more than 2-3 pads in 15 minutes).\nPlacenta not expelled 1 hour after birth of baby.",
    "source": "https://www.who.int/publications/i/item/9789241549356",
    "codes": [
      "labour",
      "vaginal_bleeding"
    ],
    "stage": "pregnancy"
  },
  {
    "id": "pcpnc-m4-no-medication",
    "title": "WHO, Pregnancy, childbirth, postpartum and newborn care: a guide for essential practice, 3rd edition (2015), M4, p. 165",
    "quote": "Do not take medication unless prescribed at the health centre.",
    "source": "https://www.who.int/publications/i/item/9789241549356",
    "codes": [],
    "stage": "postpartum"
  }
];
