// Every user-facing string lives here, keyed by id. `null` means "a human has not written this
// yet": the screen shows `[copy: <key>]`. Medical copy (LUM-47) is never written by code.
export type Lang = 'fil' | 'en';
interface Entry {
  fil: string | null;
  en: string | null;
  // A medical string never falls back to the other language.
  medical?: boolean;
}

const ui = (en: string, fil: string | null = null): Entry => ({ fil, en });
// Quoted from an approved WHO source; the English shows in Filipino slots until the team writes
// the Filipino (LUM-47), since a cited quote is safer than an empty slot.
const who = (en: string): Entry => ({ fil: null, en });

export const COPY = {
  'home.prompt': ui('How are you feeling?', "Ano'ng nararamdaman mo?"),
  'home.field.label': ui('Tell Liora how you feel'),
  'home.check': ui('Check'),
  'home.mic': ui('Record your voice'),
  'home.mic.stop': ui('Stop recording'),
  'home.recording.of': ui('of'),
  'home.privacy': ui('Stays on this phone'),
  'home.ai.on': ui('AI on'),
  'home.ai.off': ui('AI off, checklist on'),
  'home.offline': ui('Offline'),
  'home.error': ui('Something went wrong. Try again, or use the checklist.'),
  'home.dev_native': ui('Native model test'),
  'home.setup': ui('Get Liora ready for offline'),
  'home.calendar': ui('Calendar'),
  'home.voice.error': ui('Voice did not work. Please type instead.'),
  'home.log': ui('My log'),
  'home.checklist.hint': ui('Opens the checklist'),

  'result.show_nurse': ui('Show this to the nurse'),
  'result.why': ui('Why?'),
  'result.skip': ui('Skip'),
  'result.yes': ui('Yes'),
  'result.no': ui('No'),
  'result.ask_checkup': ui('Ask at your check-up'),
  'result.home': ui('Done'),
  'result.back': ui('Back'),
  'result.not_found': ui('This entry is not on this phone.'),

  'go.headline': who('Go to the hospital or health centre immediately'),
  'go.line': who('Day or night, DO NOT wait.'),
  'go.signs.header': ui('Signs in your message'),
  'go.source.header': ui('Source'),

  'followup.skip_means': ui('If you skip, Liora treats it as serious.'),

  'calm.copy': who("If at any time you have any concerns about your or your baby’s health, go to the health centre."),
  'calm.watch.header': who('Go to the hospital or health centre immediately, day or night, DO NOT wait, if any of the following signs:'),
  'calm.watch.items': who('vaginal bleeding\nconvulsions/fits\nsevere headaches with blurred vision\nfever and too weak to get out of bed\nsevere abdominal pain\nfast or difficult breathing.'),

  'nurse.weeks': ui('Weeks pregnant'),
  'nurse.days_since_birth': ui('Days since giving birth'),
  'nurse.signs': ui('Signs she reported'),
  'nurse.logged': ui('Logged'),
  'nurse.bp': ui('Blood pressure she entered'),

  'sign.vaginal_bleeding': who('Bleeding vaginally'),
  'sign.convulsions': who('Convulsing'),
  'sign.fever': who('Fever'),
  'sign.severe_headache': who('Headache'),
  'sign.visual_disturbance': who('Visual disturbance'),
  'sign.imminent_delivery': who('Imminent delivery'),
  'sign.labour': who('Labour'),
  'sign.looks_very_ill': who('Looks very ill'),
  'sign.severe_vomiting': who('Vomiting'),
  'sign.severe_pain': who('Pain'),
  'sign.severe_abdominal_pain': who('Abdominal pain'),
  'sign.unconscious': who('Unconscious'),
  'sign.central_cyanosis': who('Central cyanosis'),
  'sign.severe_difficulty_breathing': who('Difficulty breathing'),

  'severity.severe': ui('severe'),
  'severity.moderate': ui('moderate'),
  'severity.mild': ui('mild'),
  'severity.unknown': ui('not sure yet'),

  // "Sobrang sakit ba?" is the team's own wording from the demo script (HANDOFF.md section 10).
  'fu.severe_headache': ui('Is it very painful?', 'Sobrang sakit ba?'),
  'fu.severe_pain': ui('Is it very painful?', 'Sobrang sakit ba?'),
  'fu.severe_abdominal_pain': ui('Is it very painful?', 'Sobrang sakit ba?'),
  'fu.severe_vomiting': ui('Is the vomiting very bad?'),
  'fu.severe_difficulty_breathing': ui('Is it very hard to breathe?'),

  'why.title': ui('Why?'),
  'why.none': ui('Ask at your check-up'),

  // calendar and log (LUM-65, LUM-62)
  'calendar.title': ui('Calendar'),
  'calendar.prev': ui('Previous month'),
  'calendar.next': ui('Next month'),
  'calendar.mark_start': ui('Mark period start'),
  'calendar.mark_end': ui('Mark period end'),
  'calendar.no_entries': ui('Nothing logged this day'),
  'calendar.next_period': ui('Next period around {date}'),
  'calendar.window': ui('It could start between {from} and {to}'),
  'calendar.basis.history': ui('Based on your logged periods'),
  'calendar.basis.stated': ui('Based on the cycle length you told Liora'),
  'calendar.confidence.low': ui('Confidence: low'),
  'calendar.confidence.medium': ui('Confidence: medium'),
  'calendar.confidence.high': ui('Confidence: high'),
  'calendar.not_birth_control': ui('Not for birth control.'),
  'calendar.need_period': ui('Mark a period start and Liora can estimate the next one'),
  'calendar.no_estimate_status': ui('No period estimate while pregnant or after giving birth.'),
  'calendar.confirm_start': ui('Started {date}, tama ba?'),
  'calendar.confirm_end': ui('Ended {date}, tama ba?'),
  'calendar.legend': ui('Solid: logged. Dashed: estimated.'),
  'calendar.day.logged': ui('period day, logged'),
  'calendar.day.estimated': ui('period day, estimated'),
  'calendar.day.today': ui('today'),
  'calendar.day.symptoms': ui('symptoms logged'),
  'calendar.day.mood': ui('mood logged'),
  'log.title': ui('My log'),
  'log.privacy': ui('Stays on this phone'),
  'log.empty': ui('Nothing logged yet'),
  'log.group.period': ui('Period'),
  'log.group.symptoms': ui('Symptoms'),
  'log.group.mood': ui('Mood'),
  'log.group.pregnancy': ui('Pregnancy'),
  'log.delete_entry': ui('Delete this entry'),
  'log.delete_all': ui('Delete everything'),
  'log.delete_all.confirm': ui('Delete everything on this phone? This cannot be undone.'),
  'log.cancel': ui('Cancel'),

  // setup and checklist (LUM-71, LUM-64)
  'setup.title': ui('Getting Liora ready for offline'),
  'setup.wifi': ui('Use Wi-Fi. The download is large.'),
  'setup.model.gemma': ui('Gemma 4'),
  'setup.model.voice': ui('Voice add-on'),
  'setup.model.cards': ui('Source card search'),
  'setup.done': ui('Ready'),
  'setup.web': ui('Not available on web'),
  'setup.failed': ui('Download did not finish. Try again on Wi-Fi.'),
  'setup.retry': ui('Try again'),
  'setup.mb': ui('MB'),
  'setup.download': ui('Download'),
  'setup.q.status': ui('Where are you now?'),
  'setup.status.pregnant': ui('Pregnant'),
  'setup.status.postpartum': ui('Recently gave birth'),
  'setup.status.neither': ui('Neither'),
  'setup.weeks': ui('Weeks pregnant'),
  'setup.days': ui('Days since birth'),
  'setup.last_period': ui('Last period started (YYYY-MM-DD)'),
  'setup.cycle_length': ui('Usual cycle length in days'),
  'setup.invalid': ui('Check the number or date'),
  'setup.save': ui('Save and continue'),
  'setup.skip': ui('Skip for now'),
  'checklist.title': ui('Check the signs'),
  'checklist.check': ui('Check'),
  'checklist.none': ui('Choose at least one'),
  // mood and crisis (LUM-63)
  // The two mood results and the crisis headline are team phrases, not quotes; the team confirms them (LUM-47).
  'home.mood': ui('Mood check'),
  'mood.of': ui('of'),
  'mood.back': ui('Back'),
  'mood.result.high': ui('Please talk about these answers with a health worker at your next check-up.'),
  'mood.result.low': ui('Thank you. Your answers stay on this phone.'),
  'mood.done': ui('Done'),
  'crisis.headline': ui('Talk to someone now.'),
  'crisis.call': ui('Call 1553'),
  'crisis.source': ui('WHO Philippines and DOH, 10 September 2020'),
  // how liora decided (LUM-76)
  'decided.link': ui('How Liora decided'),
  'decided.title': ui('How Liora decided'),
  'decided.reader.lexicon': ui('Word list'),
  'decided.reader.embedding': ui('Meaning match'),
  'decided.reader.llm': ui('AI typed decisions'),
  'decided.reader.checklist': ui('Checklist'),
  'decided.nothing': ui('Found nothing'),
  'decided.conf.high': ui('very likely'),
  'decided.conf.mid': ui('likely'),
  'decided.conf.low': ui('possible'),
  'decided.rules': ui('Rules that fired'),
  'decided.rules.none': ui('No rule fired'),
  'decided.models': ui('Models that ran'),
  'decided.models.none': ui('No AI model ran; the word list and rules decided.'),
  // name, lock and settings (LUM-81, LUM-82)
  'name.question': ui('What should Liora call you?'),
  'name.optional': ui('Optional. It stays on this phone.'),
  'home.greeting': ui('Hi, {name}'),
  'home.settings': ui('Settings'),
  'settings.title': ui('Settings'),
  'settings.name.save': ui('Save name'),
  'settings.lock': ui('Lock my private history with Face ID'),
  'lock.title': ui('Unlock with Face ID'),
  'lock.body': ui('Your log, mood checks and calendar are locked on this phone.'),
  'lock.button': ui('Unlock'),
  'lock.prompt': ui('Unlock your private history'),
  'lock.fallback': ui('Use passcode'),
  'tabs.today': ui('Today'),
  'tabs.calendar': ui('Calendar'),
  'tabs.liora': ui('Liora'),
  'tabs.profile': ui('Profile'),
  // companion (LUM-84): team phrases that only point to her data, the rules or a quoted card
  'companion.symptom.go_now': ui('This needs care now. Here is what the WHO rules say.'),
  'companion.symptom.follow_up': ui('One question first, so the rules can decide.'),
  'companion.symptom.ok': ui('Here is what the rules found.'),
  'companion.period.heard': ui('Shall I put this on your calendar?'),
  'companion.period.when': ui('When did it start? You can mark it on the calendar.'),
  'companion.mood.noted': ui('Thank you for telling me. I noted how you feel.'),
  'companion.cycle.pregnant': ui('While you are pregnant, Liora does not estimate periods.'),
  'companion.cycle.postpartum': ui('After birth, periods can take a while to return. Log one when it comes.'),
  'companion.cycle.no_data': ui('Log at least two periods and I can estimate the next one.'),
  'companion.health.card': ui('This is the closest reviewed source I have, word for word.'),
  'companion.health.ask': ui('I do not have a reviewed source for that. Ask at your check-up.'),
  'companion.greeting': ui('Hi, {name}. How are you feeling today?'),
  'companion.greeting.anon': ui('Hi. How are you feeling today?'),
  'companion.other': ui('Tell me how you feel, log your period, or ask about your cycle.'),
  'companion.action.checklist': ui('Danger-sign checklist'),
  'companion.action.mood_check': ui('Mood check'),
  'companion.action.calendar': ui('Calendar'),
  'companion.action.log_period': ui('Log period'),
  // profile and today (LUM-85)
  'profile.about': ui('About you'),
  'profile.name': ui('Name'),
  'profile.age': ui('Age'),
  'profile.height': ui('Height (cm)'),
  'profile.weight': ui('Weight (kg)'),
  'profile.range': ui('Enter a number from {min} to {max}.'),
  'profile.pregnancy': ui('Pregnancy'),
  'profile.cycle': ui('Cycle'),
  'profile.period_length': ui('Period length in days'),
  'profile.privacy': ui('Privacy'),
  'profile.ai': ui('AI models'),
  'profile.ai.open': ui('Set up models'),
  'profile.unit.years': ui('years'),
  'profile.unit.cm': ui('cm'),
  'profile.unit.kg': ui('kg'),
  'profile.unit.days': ui('days'),
  'today.cycle_day': ui('Cycle day'),
  'today.next_period': ui('Next period around'),
  'today.date_hint': ui('Today'),
  'today.quick': ui('Quick actions'),
  'today.talk': ui('Talk to Liora'),
  'today.checklist': ui('Checklist'),
  // calendar and period tracking (LUM-65)
  'cal.log_period': ui('Log period'),
  'cal.cycle_day': ui('Cycle day'),
  'cal.of_days': ui('of about {n} days'),
  'cal.weeks_pregnant': ui('{n} weeks pregnant'),
  'cal.weeks_unknown': ui('Pregnant'),
  'cal.postpartum': ui('When your period returns, log it here.'),
  'cal.history': ui('Cycle history'),
  'cal.history.days': ui('{n} days'),
  'cal.history.running': ui('Current cycle'),
  'cal.history.empty': ui('Your past cycles will show here once you log two periods.'),
  'cal.day.period': ui('Period'),
  'cal.day.period_range': ui('{from} to {to}'),
  'cal.day.ongoing': ui('{from}, still going'),
  'cal.day.flow': ui('Flow: {flow}'),
  'cal.day.edit': ui('Edit period'),
  'cal.day.delete': ui('Delete period'),
  'cal.day.open': ui('Open entry'),
  'cal.day.mood': ui('Mood logged'),
  'cal.period.title': ui('Log a period'),
  'cal.period.edit_title': ui('Edit period'),
  'cal.period.start': ui('Start date'),
  'cal.period.end': ui('End date'),
  'cal.period.add_end': ui('Add an end date'),
  'cal.period.remove_end': ui('Remove end date'),
  'cal.period.flow': ui('Flow'),
  'cal.period.save': ui('Save'),
  'cal.period.cancel': ui('Cancel'),
  'cal.period.prev_day': ui('Day earlier'),
  'cal.period.next_day': ui('Day later'),
  'cal.period.end_before': ui('The end date comes before the start.'),
  'cal.flow.light': ui('Light'),
  'cal.flow.medium': ui('Medium'),
  'cal.flow.heavy': ui('Heavy'),
  // companion thread (LUM-84)
  'liora.empty.title': ui('Kumusta? Tell Liora how you feel.'),
  'liora.empty.body': ui('Type or speak in Taglish. The rules decide; I only listen and point.'),
  'liora.starter.1': ui('Masakit ulo ko'),
  'liora.starter.2': ui('Nagsimula regla ko ngayon'),
  'liora.starter.3': ui('Kailan next period ko?'),
  'liora.placeholder': ui('Message Liora'),
  'liora.send': ui('Send'),
  'liora.live': ui('Liora Live'),
  'live.close': ui('Close'),
  'live.listening': ui('Listening. Liora answers when you pause.'),
  'live.thinking': ui('Thinking…'),
  'live.speaking': ui('Liora is speaking. Tap the orb to interrupt.'),
  'live.retry': ui('I did not catch that. Tap the orb to try again.'),
  'live.orb': ui('Liora Live orb'),
  'voice.mic_denied': ui('Liora needs the microphone. Turn it on in Settings.'),
  'voice.settings': ui('Open Settings'),
  'liora.voice.setup': ui('Voice needs the offline download first.'),
  'liora.voice.setup.open': ui('Get Liora ready'),
  'liora.voice.writing': ui('Writing down what you said…'),
  'liora.typing': ui('Liora is thinking'),
  'liora.period.add': ui('Add to calendar'),
  'liora.period.skip': ui('Not now'),
  'liora.period.added': ui('Added to your calendar.'),
  'liora.go.open': ui('Open and show the nurse'),
  'liora.followup.open': ui('Answer the question'),
  'liora.error': ui('Something went wrong. Please try again.'),
  'liora.clear': ui('Clear conversation'),
  // her mood words, shown back as she said them
  'feeling.calm': ui('Calm'),
  'feeling.joyful': ui('Joyful'),
  'feeling.energetic': ui('Energetic'),
  'feeling.romantic': ui('Romantic'),
  'feeling.tired': ui('Tired'),
  'feeling.anxious': ui('Anxious'),
  'feeling.stressed': ui('Stressed'),
  'feeling.irritable': ui('Irritable'),
  'feeling.sad': ui('Sad'),
  // today's glance and "Liora noticed" (LUM-60): her own logs, counted; never advice
  'insight.title': ui('Liora noticed'),
  'insight.basis': ui('Counted from what you logged on this phone.'),
  'insight.cycle_length': ui('Your cycles average {days} days, from {cycles} cycles.'),
  'insight.cycle_spread': ui('Your cycles ranged from {min} to {max} days.'),
  'insight.last_cycle': ui('Your last cycle was {days} days; your average is {average}.'),
  'insight.period_length': ui('Your periods last about {days} days, from {periods} periods.'),
  'insight.recurring': ui('You mentioned {what} {count} times in the last {days} days.'),
  'insight.recurring.danger': ui('If it is happening now, tell Liora so the rules can check it.'),
  'insight.mood_pattern': ui('You felt {mood} {count} times in the last {days} days.'),
  'insight.mood_check.since': ui('It has been {days} days since your last mood check.'),
  'insight.mood_check.never': ui('You have not done a mood check yet.'),
  'insight.empty': ui('Tell Liora how you feel, log your period or a mood, and your patterns will show here.'),
  'glance.title': ui('This week'),
  'glance.checkins': ui('Check-ins'),
  'glance.moods': ui('Moods'),
  'glance.cycle': ui('Cycle'),
  'glance.average_cycle': ui('Average cycle'),
  'glance.last_cycle': ui('Last cycle'),
  'glance.period_length': ui('Period length'),
  'glance.days': ui('{n} days'),
  'glance.none': ui('Nothing yet'),
  'glance.level.go_now': ui('Go now'),
  'glance.level.follow_up': ui('Follow-up'),
  'glance.level.ok': ui('Calm'),
  'today.card_title': ui('From the reviewed sources'),
  'symptom.cramps': ui('Cramps'),
  'symptom.headache': ui('Headache'),
  'symptom.back_pain': ui('Back pain'),
  'symptom.bloating': ui('Bloating'),
  'symptom.fatigue': ui('Tiredness'),
  'symptom.mood_changes': ui('Mood changes'),
  'symptom.acne': ui('Acne'),
  'symptom.breast_tenderness': ui('Breast tenderness'),
  'symptom.sleep_quality': ui('Sleep'),
  'symptom.energy': ui('Energy'),
  'symptom.stress': ui('Stress'),
  'symptom.appetite': ui('Appetite'),
  'symptom.nausea': ui('Nausea'),
  'symptom.pelvic_pain': ui('Pelvic pain'),
  // native pickers and profile edit (LUM-85)
  'profile.edit.title': ui('Your details'),
  'profile.edit.open': ui('Edit your details'),
  'profile.edit.save': ui('Save'),
  'profile.edit.status': ui('Status'),
  'profile.edit.height': ui('Height'),
  'profile.edit.weight': ui('Weight'),
  'profile.edit.not_set': ui('Not set'),
  'profile.unit.weeks': ui('weeks'),
  // day log (LUM-65)
  'daylog.title': ui('Log your day'),
  'daylog.date': ui('Date'),
  'daylog.period': ui('Period'),
  'daylog.symptoms': ui('Symptoms'),
  'daylog.moods': ui('Mood'),
  'daylog.activities': ui('Activities'),
  'daylog.note': ui('Note'),
  'daylog.note.label': ui('A note for this day'),
  'daylog.flow.none': ui('None'),
  'daylog.save': ui('Save'),
  'daylog.cancel': ui('Cancel'),
  'daylog.clear': ui('Clear this day'),
  'daylog.button': ui('Log this day'),
  'daylog.edit_button': ui('Edit this day'),
  'daylog.shown': ui('Logged'),
  'activity.walk': ui('Walk'),
  'activity.exercise': ui('Exercise'),
  'activity.rest': ui('Rest'),
  'activity.water': ui('Water'),
  'activity.slept_well': ui('Slept well'),
  'activity.checkup_visit': ui('Check-up visit'),
  'activity.medicine_taken': ui('Medicine taken as prescribed'),
  // today page (LUM-60)
  'today.log': ui('Log today'),
  'today.weeks_title': ui('{n} weeks pregnant'),
  'today.cycle_title': ui('Cycle day {n}'),
  'today.next_around': ui('Next period around {date}'),
  'today.window': ui('Most likely {from} to {to}'),
  'today.invite': ui('Your cycle starts here'),
  'today.invite_note': ui('Log a period and Liora will count your days from it.'),
  'today.cycles_title': ui('Your cycles'),
  'today.now': ui('Now'),
  'today.profile_hint': ui('Open your profile'),
  // today: her cycle at a glance (LUM-60); dates and counts from her logs only
  'td.first_run': ui('Log your last period'),
  'td.first_run.sub': ui('Liora estimates your next period from what you log.'),
  'td.pregnant': ui('Week {n}'),
  'td.pregnant.unknown': ui('Pregnant'),
  'td.pregnant.sub': ui('Pregnant, from your profile'),
  'td.postpartum': ui('After birth'),
  'td.postpartum.sub': ui('Log a period when it returns.'),
  'td.period': ui('Period, day {n}'),
  'td.countdown': ui('Period in {from}–{to} days'),
  'td.countdown.one_value': ui('Period in {n} days'),
  'td.countdown.tomorrow': ui('Period could start tomorrow'),
  'td.any_day': ui('Period could start any day'),
  'td.past_window': ui('Cycle day {n}'),
  'td.past_window.sub': ui('Past your estimated window'),
  'td.cycle_day': ui('Cycle day {n}'),
  'td.confidence.low': ui('Estimated, low confidence'),
  'td.confidence.medium': ui('Estimated, medium confidence'),
  'td.confidence.high': ui('Estimated, high confidence'),
  'td.action.period': ui('Period'),
  'td.action.symptoms': ui('Symptoms'),
  'td.action.mood': ui('Mood'),
  'td.action.more': ui('More'),
  'td.action.done': ui('Logged today'),
  'td.next.days': ui('Next period, likely in {n} days'),
  'td.next.tomorrow': ui('Next period, likely tomorrow'),
  'td.next.now': ui('Next period, could start now'),
  'td.next.range': ui('{from} to {to}'),
  'td.next.history': ui('From {n} logged cycles.'),
  'td.next.stated': ui('From the cycle length you gave.'),
  'td.confidence_short.low': ui('Low confidence'),
  'td.confidence_short.medium': ui('Medium confidence'),
  'td.confidence_short.high': ui('High confidence'),
  'td.track': ui("Replayed on your last {n} cycles, Liora's window held {k}."),
  'td.patterns_after': ui('Liora describes patterns after 2 logged cycles. You have {n}.'),
  'td.unwell.title': ui('Feeling unwell?'),
  'td.unwell.body': ui('Tell Liora in your own words. The WHO danger-sign rules decide when to go.'),
  'td.unwell.action': ui('Tell Liora'),
  'td.cycles': ui('Your cycles'),
  'td.cycle_length': ui('Cycle length'),
  'td.cycle_length.range': ui('{min} to {max} days'),
  'td.cycle_length.sub': ui('Averaging about {avg} days, from {n} cycles'),
  'td.cycle_length.sub_one': ui('{avg} days, from 1 cycle'),
  'td.period_length': ui('Period length'),
  'td.period_length.value': ui('About {n} days'),
  'td.period_length.sub': ui('From {n} logged periods'),
  'td.period_length.sub_one': ui('From 1 logged period'),
  'td.last_cycle': ui('Last cycle'),
  'td.last_cycle.sub': ui('Your most recent full cycle'),
  'td.symptoms_cycle': ui('Symptoms this cycle'),
  'td.symptoms_cycle.value': ui('{n} logged'),
  'td.days': ui('{n} days'),
  'td.day_one': ui('1 day'),
  'td.none': ui('Nothing yet'),
  'td.row.current': ui('Current cycle, from {date}'),
  'td.row.day': ui('Day {n}'),
  'td.row.range': ui('{from} to {to}'),
  'td.see_calendar': ui('See all in Calendar'),
  'td.key.period': ui('Period'),
  'td.key.estimated': ui('Estimated'),
  'td.deeper': ui('Deeper patterns'),
  'td.gap.question': ui('Did you have a period since {date}?'),
  'td.gap.detail': ui('This cycle has run {n} days, about twice your usual length.'),
  'td.gap.yes': ui('Yes, log it'),
  'td.gap.no': ui('No, it was a long cycle'),
  'td.open_profile': ui('Open your profile'),
  'td.open_calendar': ui('Open the calendar'),
  // calendar, month and year (LUM-65): her marks and Liora's estimates, in words
  'cal2.month': ui('Month'),
  'cal2.year': ui('Year'),
  'cal2.edit': ui('Edit period dates'),
  'cal2.edit.title': ui('Tap the days you had your period.'),
  'cal2.edit.sub': ui('Liora marks your usual {n} days. Tap the first day again to remove them.'),
  'cal2.save': ui('Save'),
  'cal2.cancel': ui('Cancel'),
  'cal2.today': ui('Today'),
  'cal2.back_today': ui('Back to Today'),
  'cal2.log_day': ui('Log this day'),
  'cal2.preview.cycle_day': ui('Cycle day {n}'),
  'cal2.preview.period_logged': ui('Period, day {n}'),
  'cal2.preview.period_estimated': ui('Expected period, day {n}'),
  'cal2.preview.window': ui('Liora estimates your next period between {from} and {to}, with {confidence}.'),
  'cal2.confidence.low': ui('low confidence'),
  'cal2.confidence.medium': ui('medium confidence'),
  'cal2.confidence.high': ui('high confidence'),
  'cal2.preview.logged': ui('What you logged'),
  'cal2.preview.nothing': ui('Nothing logged this day.'),
  'cal2.preview.checkins': ui('{n} check-ins with Liora'),
  'cal2.preview.checkin_one': ui('1 check-in with Liora'),
  'cal2.year.period': ui('Period {from}–{to}'),
  'cal2.year.expected': ui('Expected {from}–{to}'),
  'cal2.year.summary': ui('{logged} periods logged, {expected} expected'),
  'cal2.key.logged': ui('Period'),
  'cal2.key.estimated': ui('Estimated'),
  'cal2.key.today': ui('Today'),
  'cal2.pregnant': ui('While you are pregnant, Liora does not estimate periods.'),
  // day log sheet (LUM-65)
  'daylog.done': ui('Done'),
  'daylog.footnote': ui('Tap what fits today. Every tap is saved.'),
  'daylog.days': ui('Pick a day'),
  // profile page (LUM-85)
  'pf.edit': ui('Edit'),
  'pf.day': ui('Day {n}'),
  'pf.usually': ui('usually {n} days'),
  'pf.pregnant': ui('Pregnant'),
  'pf.pregnant_week': ui('Pregnant · week {n}'),
  'pf.after_birth': ui('After birth'),
  'pf.cycle': ui('Your cycle'),
  'pf.cycle_length': ui('Cycle length'),
  'pf.cycles_logged': ui('Cycles logged'),
  'pf.about_footer': ui('Optional, and only you see them.'),
  'pf.avatar': ui('Your picture'),
  'pf.avatar.change': ui('Change your picture'),
  'pf.avatar.mark': ui('Picture {n}'),
  'pf.ai.on': ui('On'),
  'pf.ai.off': ui('Off'),
  // onboarding (LUM-71)
  'onboarding.brand': ui('Liora'),
  'onboarding.welcome.title': ui('Welcome to Liora'),
  'onboarding.welcome.line': ui('Know when to go, even with no signal.'),
  'onboarding.continue': ui('Continue'),
  'onboarding.skip': ui('Skip'),
  'onboarding.back': ui('Back'),
  'onboarding.step': ui('Step {n} of {total}'),
  'onboarding.status.line': ui('This helps Liora ask you the right questions.'),
  'onboarding.last_period': ui('Last period started'),
  'onboarding.about.line': ui('Only what you want to share. You can change it later in Profile.'),
  'onboarding.download.title': ui('Get Liora ready for offline'),
  'onboarding.download_all': ui('Download all'),
  'onboarding.start': ui('Start using Liora'),
  'onboarding.downloading': ui('Downloading'),
  // fertile window: an estimate from her cycle history, never contraception (sources in the text)
  'fertile.title': ui('Fertile window, estimated'),
  'fertile.range': ui('{from} to {to}'),
  'fertile.ovulation': ui('Likely ovulation {from} to {to}'),
  'fertile.not_contraception': ui('An estimate, not contraception.'),
  'fertile.basis': ui('Ovulation is placed 12 to 14 days before your estimated period, and the fertile window is the five days before it through ovulation.'),
  'fertile.source': ui('Bull et al., npj Digital Medicine, 2019 (luteal phase mean 12.4 days, 95% range 7 to 17; authors linked to a cycle-tracking app). Wilcox, Weinberg and Baird, NEJM, 1995 (conception only from intercourse in the six days ending on ovulation).'),
  'fertile.withheld': ui('Liora hides the fertile window when your logged cycles vary by more than 7 days.'),
  'fertile.low': ui('Low confidence: from the cycle length you gave or only a few cycles. It gets surer as you log periods.'),
  'fertile.key.window': ui('Fertile, estimated'),
  'fertile.key.ovulation': ui('Likely ovulation'),
  'fertile.day.window': ui('In the estimated fertile window'),
  'fertile.day.ovulation': ui('Likely ovulation day, estimated'),
  'profile.cycle.stated': ui('Usual cycle length'),
  'profile.period.stated': ui('Usual period length'),
  'profile.cycle.footer': ui('Liora uses these until you have logged enough periods; it never assumes 28 days.'),
  // the agent: warm fallbacks (non-medical) and what it saved or asks to save (LUM-84)
  'warm.worried': ui("I'm here with you. Let's look at this together."),
  'warm.sad': ui("Thank you for telling me. You don't have to carry this alone."),
  'warm.tired': ui('That sounds tiring. Be gentle with yourself today.'),
  'warm.happy': ui("I'm so glad to hear from you."),
  'warm.neutral': ui('Thank you for checking in with me.'),
  'agent.logged.title': ui('Saved'),
  'agent.logged.period_start': ui('Period started {date}'),
  'agent.logged.period_end': ui('Period ended {date}'),
  'agent.logged.flow': ui('{flow} flow, {date}'),
  'agent.logged.symptoms': ui('{list}, {date}'),
  'agent.logged.moods': ui('Feeling {list}, {date}'),
  'agent.logged.activities': ui('{list}, {date}'),
  'agent.logged.weeks': ui('Week {n} of your pregnancy'),
  'agent.date.today': ui('today'),
  'agent.date.yesterday': ui('yesterday'),
  'agent.undo': ui('Undo'),
  'agent.undone': ui('Undone. Nothing was saved.'),
  'agent.confirm.title': ui('Shall I save this?'),
  'agent.confirm.yes': ui('Save'),
  'agent.confirm.no': ui('Not now'),
  'agent.confirm.weeks': ui('Set you as pregnant, week {n}'),
  'agent.confirm.period_start': ui('Period started, but when?'),
  'agent.confirm.period_end': ui('Period ended, but when?'),
  'agent.confirm.replace': ui('This changes a period you already logged.'),
  'agent.tell.placeholder': ui('Tell Liora, like "Niregla ako today"'),
  'agent.tell.send': ui('Tell Liora'),
} as const satisfies Record<string, Entry>;

export type CopyKey = keyof typeof COPY;

const SEVERITY_KEYS = ['mild', 'moderate', 'severe', 'unknown'] as const;

// Keys built from data (`fu.<code>`, `sign.<code>`, `severity.<level>`) are medical, not yet written.
export function copyText(key: string, lang: Lang): string {
  const entry = (COPY as Record<string, Entry>)[key];
  if (!entry) return `[copy: ${key}]`;
  const own = entry[lang];
  if (own !== null) return own;
  if (entry.medical) return `[copy: ${key}]`;
  return entry[lang === 'fil' ? 'en' : 'fil'] ?? `[copy: ${key}]`;
}

export const fil = (key: string): string => copyText(key, 'fil');
export const en = (key: string): string => copyText(key, 'en');

export const signKey = (code: string): string => `sign.${code}`;
export const severityKey = (level: string): string =>
  (SEVERITY_KEYS as readonly string[]).includes(level) ? `severity.${level}` : `severity.unknown`;
export const followUpKey = (questionId: string): string => questionId;
