// Turns the reviewed candidates (sources/candidates.json) into the app's source cards. Only cards
// the review approved ship, quoted exactly; a link marked "?" waits for a person to confirm it.
import { readFileSync, writeFileSync } from 'node:fs';

const vocabulary = readFileSync('src/core/vocabulary.ts', 'utf8');
const dangerList = vocabulary.match(/DANGER_CODES = \[([\s\S]*?)\] as const/);
if (!dangerList) throw new Error('DANGER_CODES not found in src/core/vocabulary.ts');
const DANGER = new Set([...dangerList[1].matchAll(/'([a-z_]+)'/g)].map((m) => m[1]));

// A sign the review proposed with "+" that the rules now carry under the WHO name.
const RENAMED = { '+difficulty_breathing': 'severe_difficulty_breathing' };

const candidates = JSON.parse(readFileSync('sources/candidates.json', 'utf8'));
const cards = candidates
  .filter((c) => c.check?.verdict === 'approve')
  .map((c) => {
    const { org, title, year, page, label, url } = c.citation;
    const where = label ? `${label}, p. ${page}` : `p. ${page}`;
    return {
      id: c.id,
      title: `${org}, ${title}${year ? ` (${year})` : ''}, ${where}`,
      quote: c.body,
      source: url,
      codes: c.codes.map((code) => RENAMED[code] ?? code).filter((code) => DANGER.has(code)),
      stage: c.stage,
    };
  });

const out =
  '// Generated by scripts/build-cards.mjs from sources/candidates.json; do not edit by hand.\n' +
  "import type { CardData } from './cards';\n\n" +
  `export const CARD_DATA: CardData[] = ${JSON.stringify(cards, null, 2)};\n`;
writeFileSync('src/content/cards.data.ts', out);
console.log(`wrote ${cards.length} approved cards`);
